Local to NCMB
haruto861/Seek_ pull request #14
Opened 2021-03-12 09:20 UTC by haruto861

@yamataku29 
NCMBで取得したデータをAppDelegate内で取得するのではなく、Menuクラスに格納しました◎
次はstep2のMenuCollectionViewにデータを渡すところにチャレンジします💡

2021-03-12 11:03 UTC, yamataku29 reviewed
いくつかレビューコメントを入れておきました💁‍♂️

2021-03-12 11:03 UTC, yamataku29 commented on Seek/Controllers/MenuCollectionViewController.swift
> +        query?.findObjectsInBackground({ [self] (results, error) in
この`collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath)`はUICollectionCellが表示される度に何度も実行されるメソッドなので、このタイミングでサーバーからデータを取得する処理を入れるのは不適切なのですね🙅‍♂️
※試しにprint文を書いてログを見てみてください。

正しいタイミングとしては、この画面が表示された時なので、`viewDidLoad()`や`viewWillAppear()`内で実行するのが良さそうですね👌

2021-03-12 11:03 UTC, yamataku29 commented on Seek/Extensinos/Customize.swift
> +import Foundation
使用していないファイルは削除しましょう💁‍♂️

2021-03-13 05:13 UTC, haruto861 commented
ありがとうございます！
再度修正してPRさせていただきます！◎

2021-03-13 06:38 UTC, haruto861 reviewed
@yamataku29 
データの取得をviewDidLoad()に変更しました◎

2021-03-13 06:40 UTC, yamataku29 commented
またレビューが必要な場合はメンション付きでレビュー依頼のコメントをしてください👌

2021-03-13 07:10 UTC, haruto861 commented
> またレビューが必要な場合はメンション付きでレビュー依頼のコメントをしてください👌

こちらレビューをお願いします🙇‍♂️

2021-03-13 08:05 UTC, yamataku29 commented on Seek/AppDelegate.swift
> +
こちらがまだ未対応のようです。

2021-03-13 08:06 UTC, yamataku29 commented on Seek/Extensinos/Customize.swift
> +import Foundation
こちらがまだ未対応のようです。

2021-03-13 08:07 UTC, yamataku29 commented
コメントしました👌
レビューを受けた箇所は全て対応してから再度レビュー依頼をするようにしましょうね💁‍♂️

2021-03-17 05:27 UTC, haruto861 commented
@yamataku29 
新しいコミットのレビューよろしくお願いいたします◎

2021-03-17 11:25 UTC, yamataku29 commented on Seek/AppDelegate.swift
> +
ここがまだ残っています🙅‍♂️

2021-03-17 11:25 UTC, yamataku29 commented on Seek/Extensinos/Customize.swift
> +import Foundation
ここがまだ残っています🙅‍♂️

2021-03-17 11:26 UTC, yamataku29 requested changes
指摘されている点はちゃんと直しましょう。
何度も同じことを言われるのは良くないですよ🙅‍♂️
https://github.com/haruto861/Seek_/pull/14/files#r595929036
https://github.com/haruto861/Seek_/pull/14/files#r595929332

2021-03-17 12:57 UTC, haruto861 commented
見落としておりました、以後気をつけます😓

2021-03-17 23:27 UTC, yamataku29 commented
はい👍
ではまたレビューが必要な時にメンション付きでコメントください💁‍♂️

2021-03-18 05:21 UTC, haruto861 commented
@yamataku29 
指摘いただいた不要な変数を削除し、必要な箇所にprivateを付けました。よろしくお願い致します。

2021-03-18 05:30 UTC, yamataku29 commented
@haruto861 
修正についてはよいと思います👍
後はコンフリクトを解消しましょう💁‍♂️

2021-03-18 06:24 UTC, merged